#ifndef MEMORY_VISUALIZER_GLOBAL_H
#define MEMORY_VISUALIZER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MEMORY_VISUALIZER_LIB
# define MEMORY_VISUALIZER_EXPORT Q_DECL_EXPORT
#else
# define MEMORY_VISUALIZER_EXPORT Q_DECL_IMPORT
#endif

#endif // MEMORY_VISUALIZER_GLOBAL_H
